---
- name: Install and configure WordPress with multisite
  hosts: all
  become: yes
  vars:
    base_dir: "/home/beeitdna"
    wordpress_url: "https://wordpress.org/latest.zip"
    wordpress_zip: "{{ base_dir }}/latest.zip"
    wordpress_dir: "{{ base_dir }}/wordpress"
    # Direktori instalasi website (sesuaikan jika diperlukan)
    wp_install_dir: "/var/www/html/public_html/link-web.example.ac.id"
    # Apache configuration directories
    apache_sites_available: "/etc/httpd/sites-available"
    apache_sites_enabled: "/etc/httpd/sites-enabled"
    # Virtual host file name
    vhost_file: "link-web.example.ac.id.conf"
    # File wp-config.php (pastikan WordPress sudah ter-unarchive dahulu)
    wp_config_file: "{{ wp_install_dir }}/wp-config.php"
  tasks:
    - name: Tambahkan di wp-config.php di atas /* That's all, stop editing! Happy publishing. */
      blockinfile:
        path: "{{ wp_install_dir }}/wordpress/wp-config-sample.php"
        marker: "# {mark} ANSIBLE MANAGED BLOCK: WP_ALLOW_MULTISITE"
        insertafter: "/* That's all, stop editing! Happy publishing. */"
        block: |
           /* Multisite */
           define( 'WP_ALLOW_MULTISITE', true );
    - name: Tambahkan di wp-config.php di bawah define( 'WP_DEBUG', false );
      blockinfile:
        path: "{{ wp_install_dir }}/wordpress/wp-config-sample.php"
        marker: "# {mark} ANSIBLE MANAGED BLOCK: WP_MULTISITE CONFIG"
        insertafter: '/* Add any custom values between this line and the "stop editing" line. */'
        #insertafter: 'define( 'WP_DEBUG', false );'
        block: |
          define('MULTISITE', true);
          define('SUBDOMAIN_INSTALL', true);
          define('DOMAIN_CURRENT_SITE', 'link-web.example.ac.id');
          define('PATH_CURRENT_SITE', '/');
          define('SITE_ID_CURRENT_SITE', 1);
          define('BLOG_ID_CURRENT_SITE', 1);
    - name: Buat file virtual host untuk WordPress
      copy:
        dest: "{{ wp_install_dir }}/wordpress/.htaccess"
        content: |
           RewriteEngine On
           RewriteRule .* - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
           RewriteBase /
           RewriteRule ^index\.php$ - [L]

           # add a trailing slash to /wp-admin
           RewriteRule ^([_0-9a-zA-Z-]+/)?wp-admin$ $1wp-admin/ [R=301,L]

           RewriteCond %{REQUEST_FILENAME} -f [OR]
           RewriteCond %{REQUEST_FILENAME} -d
           RewriteRule ^ - [L]
           RewriteRule ^([_0-9a-zA-Z-]+/)?(wp-(content|admin|includes).*) $2 [L]
           RewriteRule ^([_0-9a-zA-Z-]+/)?(.*\.php)$ $2 [L]
           RewriteRule . index.php [L]
